### PR TITLE
Add Korean language

### PR DESCRIPTION
**Pull request by VenusGirl**

### CODE REVIEW

**Comment by kjen93** [comment]
@VenusGirl , thank you for the translation, but you forgot to translate the string 133 in KoreanBatteryModeLanguage.rc . Could you please translate that string so we can finish the translation?

**Comment by artar94** [comment]
@VenusGirl Please try the following beta version https://dl.tarcode.ru/beta/4.1.0.159/

**Comment by artar94** [comment]
@VenusGirl Please try the following beta version https://dl.tarcode.ru/beta/4.1.0.163/

**Comment by artar94** [comment]
@VenusGirl Please try the following beta version https://dl.tarcode.ru/beta/4.1.0.163/

**Comment by artar94** [comment]
@VenusGirl Please try the following beta version https://dl.tarcode.ru/beta/4.1.0.165/

**Pull request merged**
