### PR TITLE
Add Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@artar94
@kjen93

Add Italian language - New version.
I hope that now is OK.

### CODE REVIEW

**Comment by artar94** [comment]
@bovirus Please download the beta version here https://dl.tarcode.ru/beta/4.1.0.155/ and verify if your localization is displayed correctly. If you need to make some changes, please do not reopen Pull Request, just commit your changes to the same branch.

**Comment by bovirus** [comment]
I foudn a strabnge in the instalelr.
Is elect Italian at first step but during the instalaltion (64bit) appera this window

image

that of course is not italian.

**Comment by bovirus** [comment]
How can chnage the file in the current PR?

**Comment by kjen93** [comment]
> How can modify the file in the current PR?

You can modify it the same way you did it before creating this Pull Request.
When you edit a file in your repository https://github.com/bovirus/BatteryMode, this change is automatically added to this Pull Request

**Comment by kjen93** [comment]
@bovirus Please try the following beta version with fixed installer https://dl.tarcode.ru/beta/4.1.0.157/

**Comment by bovirus** [comment]
@kjen93 

I modified and fixed some issues in my current fork.
Please apply the changes to your repository.

image

It seems that I found a string not included in language file (Generic PnP moniotr).
Please check screenshot.

**Comment by artar94** [comment]
@bovirus Please try the following beta version https://dl.tarcode.ru/beta/4.1.0.159/
The string `Generic PnP moniotr` as well as the names of the power schemes are obtained from the system and are not localized.
It would also be great if you make lines 1281, 1381 and 1391 shorter.

**Comment by bovirus** [comment]
@artar94 
I reduce the lenght of strings requested.
Please check if it's ok (as lenght) now.

**Comment by artar94** [comment]
@bovirus Please try the following beta version https://dl.tarcode.ru/beta/4.1.0.161/
Could these lines be made even shorter?
image

**Comment by bovirus** [comment]
artart94

I amde the changes to reduce the string lenght.If you ca I propsoe a beterr handling of interface 

Move "Add condition" on the left
Move "Clear" up
Enlarge "left drop down list" width
Move "right drop down list" on the right and increase drop down width

Please check original and revsied

original GUI
image

revised GUI
image

**Comment by artar94** [comment]
@bovirus Please try the following beta version https://dl.tarcode.ru/beta/4.1.0.163/
I increased the width of the input fields and now everything fits:
image
Your offer will not work because there can be many triggers and conditions.

**Comment by bovirus** [comment]
OK. Thanks.
I beleive that it's a very good improvemnts for all languages.
Not English strings many times are longer than English...

**Comment by artar94** [comment]
@bovirus The release will be a little later, we have more changes that should go into it.
Thanks for the translation!

**Comment by bovirus** [comment]
@artar94 

Thanks.
Pelase take your time. ;-)

**Comment by VenusGirl** [comment]
BatteryMode version 4.1.0.165 works fine, everything works perfectly fine.

Thank you.

**Pull request merged**
