### PR TITLE
Chinese Traditional Translation

### PR DESCRIPTION
**Pull request by win98se**
Related to https://github.com/tarcode-apps/BatteryMode/pull/40

### CODE REVIEW

**Comment by artar94** [comment]
@win98se Thank you for your contribution to the development of Battery Mode!
Please try this beta version https://dl.tarcode.ru/beta/4.1.1.173 and tell me if everything is displayed well?

**Comment by win98se** [comment]
I've made according changes, please check out, thank you.

**Comment by artar94** [comment]
@win98se Please try the new beta version https://dl.tarcode.ru/beta/4.1.1.177
@jerrylususu Please also check this version as here the localization of the installer was changed.

**Comment by jerrylususu** [comment]
Just checked the version 4.1.1.177 and installed it using the installer. Everything (about Chinese Simplified translation) in the installer and the main program looks good to me.

**Comment by win98se** [comment]
Same, everything of the translations look perfectly.

**Pull request merged**
