### PR TITLE
Chinese Simplified Translation

### PR DESCRIPTION
**Pull request by jerrylususu**
This is a great app and with Chinese (Simplified) translation it should reach a border range of users. Hope this helps.

### CODE REVIEW

**Comment by artar94** [comment]
@jerrylususu Thank you for your contribution to the development of Battery Mode!
Please try this beta version https://dl.tarcode.ru/beta/4.1.1.173 and tell me if everything is displayed well?

**Comment by jerrylususu** [comment]
Hi! It mostly looks fine (with a minor fix), but there seems to be some strange artifact that I am not sure is expected. Please check the read boxes in the following screenshot. During my translation, I am not sure what's the purpose of ampersand, followed by a letter. Is that used for keyboard shortcuts? Are those letters expected to be displayed?

image

**Comment by artar94** [comment]
@jerrylususu These letters were previously used in the context menu, but now they are superfluous. Please remove them if they are not used in the context menu.

**Comment by jerrylususu** [comment]
Thanks for that explanation. I just removed them in the newest commit. You may need to release a new beta version to see if that works. (Also the Chinese Traditional translation in #41) needs to be updated.

**Comment by artar94** [comment]
@jerrylususu Please try the new beta version https://dl.tarcode.ru/beta/4.1.1.175
By the way, these letters were displayed due to the fact that they were written in lower case.

**Comment by jerrylususu** [comment]
Thanks for your fast response. I just checked the new beta version and as for Chinese Simplified translation all seems fine. Currently there is nothing more to add or change from my side. If you feel happy about it you may close the issue.

**Pull request merged**
